export const FETCH_REVIEWS_SUCCESS = "FETCH_REVIEWS_SUCCESS";
export const FETCH_REVIEWS_FAIL = "FETCH_REVIEWS_FAIL";
export const SET_IS_FETCHING = "SET_IS_FETCHING";
export const SET_SCORE_FILTER = "SET_SCORE_FILTER";
export const SET_CHANNEL_FILTER = "SET_CHANNEL_FILTER";
